services:
  nature_remo_mock_api:
    image: stoplight/prism:5
    container_name: nature_remo_mock_api
    ports:
      - 4010:4010
    command: ["mock", "-h", "0.0.0.0", "https://swagger.nature.global/swagger.json"]
  reverse_proxy:
    image: nginx:1.25.1
    container_name: reverse_proxy
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf.template
    command: bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      TOKEN: ${TOKEN}
